### ISSUE TITLE
wrapper server and photon server doesn't start

### ISSUE THREAD

**Issue by lmignon** [SmalsResearch/NominatimWrapper#2]
The following errors occurs when launching the servers with docker-compose...
```
wrapper_1    | [2021-09-20 15:38:07 +0000] [11] [ERROR] Exception in worker process
wrapper_1    | Traceback (most recent call last):
wrapper_1    |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
wrapper_1    |     worker.init_process()
wrapper_1    |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
wrapper_1    |     self.load_wsgi()
wrapper_1    |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
wrapper_1    |     self.wsgi = self.app.wsgi()
wrapper_1    |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
wrapper_1    |     self.callable = self.load()
wrapper_1    |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
wrapper_1    |     return self.load_wsgiapp()
wrapper_1    |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
wrapper_1    |     return util.import_app(self.app_uri)
wrapper_1    |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
wrapper_1    |     mod = importlib.import_module(module)
wrapper_1    |   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
wrapper_1    |     return _bootstrap._gcd_import(name[level:], package, level)
wrapper_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
wrapper_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
wrapper_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
wrapper_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
wrapper_1    |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
wrapper_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
wrapper_1    |   File "/NominatimWrapper/AddressCleanserREST.py", line 14, in <module>
wrapper_1    |     import AddressCleanserUtils
wrapper_1    |   File "/NominatimWrapper/AddressCleanserUtils.py", line 20, in <module>
wrapper_1    |     tqdm.pandas(tqdm)
wrapper_1    | TypeError: pandas() takes 1 positional argument but 2 were given
wrapper_1    | [2021-09-20 15:38:07 +0000] [7] [INFO] Shutting down: Master
wrapper_1    | [2021-09-20 15:38:07 +0000] [7] [INFO] Reason: Worker failed to boot.

```
```
photon_1     | 2021-09-20 15:38:07,649 [main] WARN  org.elasticsearch.node.Node - version [5.5.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
photon_1     | Exception in thread "main" java.lang.IllegalStateException: failed to load plugin - Plugin information:
photon_1     | Name: lang-painless
photon_1     | Description: An easy, safe and fast scripting language for Elasticsearch
photon_1     | Version: 5.5.0
photon_1     | Native Controller: false
photon_1     |  * Classname: org.elasticsearch.painless.PainlessPlugin due to jar hell
photon_1     | 	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:376)
photon_1     | 	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:140)
photon_1     | 	at org.elasticsearch.node.Node.<init>(Node.java:312)
photon_1     | 	at de.komoot.photon.elasticsearch.Server$MyNode.<init>(Server.java:55)
photon_1     | 	at de.komoot.photon.elasticsearch.Server.start(Server.java:110)
photon_1     | 	at de.komoot.photon.App.main(App.java:47)
photon_1     | Caused by: java.lang.IllegalStateException: jar hell!
photon_1     | class: org.objectweb.asm.AnnotationVisitor
photon_1     | jar1: /photon/photon_data/elasticsearch/modules/lang-painless/asm-debug-all-5.1.jar
photon_1     | jar2: /photon/photon_data/elasticsearch/modules/lang-painless/asm-debug-all.jar
photon_1     | 	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:282)
photon_1     | 	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:192)
photon_1     | 	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:374)
photon_1     | 	... 5 more
```

**Comment by vberten** [comment]
Hello, could you try the "devel" branch? I plan to merge both soon, but "devel" branch fixes Python package versions, which I hope will solve your problem.

Thanks for reporting this issue!

**Comment by lmignon** [comment]
@vberten Thank you for the fast reply. Indeed, the issue is fixed into the `devel` branch. Moreover, the ranking is also better when using the `devel` branch. Thank you for sharing this work with the community!
